name: Build-Push-Deploy-Image
on:
  push:
    branches:
      - master
      - main
      - develop
  workflow_dispatch:
    branches:
      - master
      - main
      - develop      
jobs:
  # https://docs.docker.com/ci-cd/github-actions/
  build_push_to_registry:
    name: Docker - Build and Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v2
      #   with:
      #     images: liteobject/liteobject-app:latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./LiteObject.App/Dockerfile
          push: true
          #tags: ${{ steps.meta.outputs.tags }}
          #labels: ${{ steps.meta.outputs.labels }}
          labels: "org.label-schema.schemaVersion=1.0"
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/liteobject-app:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/liteobject-app:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/liteobject-app:buildcache,mode=max
          # script: |            
          #   IMAGE_CREATED_DATE=$(docker inspect -f '{{ .Created }}' liteobject-app | date)
          #   echo "IMAGE_CREATED_DATE: $IMAGE_CREATED_DATE"
  
  ssh_conn_to_deploy:
    name: "SSH - Connect to Server and Deploy"
    needs: [build_push_to_registry]
    runs-on: ubuntu-latest
    steps:
     - name: "Test SSH Connection"
       uses: appleboy/ssh-action@master   
       env:
         WELCOME: "ssh pipeline"
         LOGIN: '${{ secrets.MAIL_SERVER_LOGIN }}'
       with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         passphrase: ${{ secrets.SSH_PASSPHRASE }}
         key: ${{ secrets.SSH_KEY }}
         port: 22
         script: |
           echo HelloWorld
           echo "LOGIN=$LOGIN"
           CREATED_ON=$(date)
           echo "CREATED_ON=$CREATED_ON"
           whoami
           docker stop liteobject-app
           docker rmi liteobject/liteobject-app           
           docker run --rm -d -p 5000:80 --name liteobject-app liteobject/liteobject-app:latest --pull=always --build-arg CREATED_ON=TODAY --env CREATED_ON=TODAY export MY_DATE=$(date)
           docker exec -it liteobject-app bash
           export IMAGE_CREATED_ON=$(date)
           printenv
           exit
           docker ps