name: Build-Push-Deploy-Image
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  build_push_to_registry:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v2
      #   with:
      #     images: liteobject/linode-app
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./LiteObject.App
          file: ./LiteObject.App/Dockerfile
          push: true
          #tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
          tags: liteobject/liteobject-app:latest
  
  ssh_conn_to_deploy:
    name: "SSH - Connect to Deploy"
    needs: [build_push_to_registry]
    runs-on: ubuntu-latest
    steps:
     - name: "Test SSH Connection"
       uses: appleboy/ssh-action@master   
       env:
         WELCOME: "ssh pipeline"
       with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         passphrase: ${{ secrets.SSH_PASSPHRASE }}
         key: ${{ secrets.SSH_KEY }}
         port: 22
         script: |
           echo $WELCOME 
           whoami
           docker ps      