name: "Docker Build and Push"
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
        - '**/*.md'
        - '**/*.gitignore'
        - '**/*.gitattributes'
env:
  APPLICATION_NAME: "LiteObject-App"
  NETCORE_VERSION: "6.0.0"
jobs:  
  docker:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    steps:
      # Buildx step is not required but recommended using it to be able to build multi-platform images, export cache, etc.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
      - name: TEST
        run: ls -l /src/LiteObject.App
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}/LiteObject.Blazor.App/src"
          push: true
          tags: liteobject/liteobject-app:latest
 
    