name: SSH - Connect to Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
jobs:
  test_conn:
    name: "Test Connection"
    runs-on: ubuntu-latest
    steps:
     - name: "Test SSH Connection"
       uses: appleboy/ssh-action@master   
       env:
         WELCOME: "ssh pipeline"
       with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         key: ${{ secrets.SSH_KEY }}
         port: 22
         script: |
           echo $WELCOME 
           cd /source/repos/LiteObject.Blazor.App
           git pull origin master
           git status
           ll
